#!/usr/bin/env python3
"""
PostGWAS Fine-Mapping CLI
Supports two engines:
  • SuSiE  (Python/R-based)
  • FINEMAP (C++ binary)
Works in:
  • DIRECT mode   → run fine-mapping on existing locus + sumstats
  • PIPELINE mode → Harmonisation → LD Blocks → QC → Formatter → Fine-mapping
"""

import argparse
import sys
from pathlib import Path
from rich_argparse import RichHelpFormatter

# =========================================================
# BACKEND RUNNERS
# =========================================================
from postgwas.finemap.workflows import (
    run_susie_direct,
)

# Shared parsers
from postgwas.clis.common_cli import (
    get_defaultresourse_parser,
    get_common_out_parser,
    get_common_susie_arguments,
    get_plink_binary_parser,
    get_finemap_method_parser
)

from postgwas.utils.main import validate_path


# =========================================================
# SHARED DIRECT-MODE INPUT ARGUMENTS
# =========================================================
def get_finemap_inputs_parser(add_help=False):
    """
    SuSiE/FINEMAP input files that exist ONLY in direct mode.
    """
    parser = argparse.ArgumentParser(add_help=add_help)
    grp = parser.add_argument_group("Fine-mapping Direct-Mode Inputs")

    grp.add_argument(
        "--locus_file",
        metavar=" ",
        type=validate_path(must_exist=True, must_be_file=True),
        help=(
            "[bold bright_red]Required[/bold bright_red]: "
            "Locus definition file (one row per locus). Must contain columns: CHR, START, END."
        )
    )

    grp.add_argument(
        "--finemap_input_file",
        metavar=" ",
        type=validate_path(must_exist=True, must_be_file=True),
        help=(
            "[bold bright_red]Required[/bold bright_red]: "
            "Fine-mapping–ready summary statistics file. "
            "Should be generated by the postgwas formatter module."
        )
    )

    return parser


# =========================================================
# MAIN CLI - DIRECT MODE ONLY
# =========================================================
def main():

    # 1. Setup the single, top-level parser, including ONLY Direct Mode components
    parser = argparse.ArgumentParser(
        prog="postgwas-finemap",
        description=(
            "SuSiE / FINEMAP fine-mapping module (Direct Mode Only).\n"
            "Runs fine-mapping using existing sumstats and locus file."
        ),
        formatter_class=RichHelpFormatter,
        parents=[
            # --- Common Components ---
            get_defaultresourse_parser(),
            get_common_out_parser(),
            get_finemap_method_parser(), # Defines --finemap_method
            get_common_susie_arguments(),
            get_plink_binary_parser(),
            
            # --- Direct Mode specific inputs ---
            get_finemap_inputs_parser(), # Defines sumstat/locus file inputs
        ],
    )

    # If no arguments provided → show help
    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(0)
    
    # 3. Execution and Dispatch
    args = parser.parse_args()

    # Dispatch logic based only on --finemap_method
    if args.finemap_method == "susie":
        run_susie_direct(args)
    elif args.finemap_method == "finemap":
        print("FINEMAP method selected. FINEMAP is not yet implemented.")
    else:
        # This branch should ideally not be reached if choices are used for --finemap_method
        print(f"Error: Unknown fine-mapping method '{args.finemap_method}'.")


if __name__ == "__main__":
    main()
    
