# =====================================================================
# Base Image
# =====================================================================
FROM mambaorg/micromamba:1.4.2

USER root

# =====================================================================
# System dependencies
# =====================================================================
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc g++ make wget git curl bzip2 unzip \
        libcurl4-openssl-dev libsuitesparse-dev \
        zlib1g-dev libbz2-dev liblzma-dev \
        ca-certificates pkg-config \
        libssl-dev libxml2-dev pigz \
        libharfbuzz-dev \
        gnupg \
        libfribidi-dev \
        libfreetype6-dev \
        libpng-dev \
        libtiff5-dev \
        libjpeg-dev \
        libfontconfig1-dev \
        libgit2-dev \
        libxml2-dev \
        libcurl4-openssl-dev \
        libssl-dev \
        libeigen3-dev \
        procps && \
    rm -rf /var/lib/apt/lists/*

# =====================================================================
# 1. MAIN ENV: PostGWAS (Create Env & Install Deps)
# =====================================================================
COPY environment.yml /tmp/environment.yml

# 1. Create the base environment
RUN micromamba create -y -n postgwas -f /tmp/environment.yml && \
    micromamba clean --all --yes

# 2. Install Build Tools & R Base into the Conda Env
#    (We install R here so it lives inside the 'postgwas' env)
RUN micromamba install -y -n postgwas -c conda-forge \
        cmake \
        mkl \
        mkl-include \
        sysroot_linux-64 \
        gcc_linux-64 \
        gxx_linux-64 \
        r-base \
        r-xml2 \
        libxml2 \
        r-matrix \
        r-data.table \
        r-survey && \
    micromamba clean --all --yes

# 3. Explicitly install 'remotes' and 'GSMR2' using R's internal manager
RUN micromamba run -n postgwas Rscript -e "install.packages('remotes', repos='https://cloud.r-project.org'); remotes::install_github('jianyanglab/gsmr2', dependencies=TRUE)"

ENV PATH="/opt/conda/envs/postgwas/bin:$PATH"

# =====================================================================
# 2. VEP ENV
# =====================================================================
RUN micromamba create -y -n vep \
      -c conda-forge -c bioconda \
      ensembl-vep=113 && \
    micromamba clean --all --yes

# =====================================================================
# 3. LDSC ENV
# =====================================================================
RUN micromamba create -y -n ldsc \
        -c conda-forge -c bioconda \
        python=2.7 \
        numpy=1.16 \
        scipy=1.2.1 \
        pandas=0.24.2 \
        bitarray \
        nose \
        pybedtools && \
    micromamba clean --all --yes

WORKDIR /opt
RUN git clone https://github.com/bulik/ldsc.git

# =====================================================================
# Build HTSlib + BCFtools + Freeseek Plugins
# =====================================================================
WORKDIR /opt/tools
SHELL ["/bin/bash", "-c"]

RUN wget https://github.com/samtools/bcftools/releases/download/1.22/bcftools-1.22.tar.bz2 && \
    wget https://github.com/samtools/htslib/releases/download/1.22/htslib-1.22.tar.bz2 && \
    tar -xvjf bcftools-1.22.tar.bz2 && \
    tar -xvjf htslib-1.22.tar.bz2

WORKDIR /opt/tools/htslib-1.22
RUN ./configure --enable-libcurl --prefix=/usr/local && \
    make -j && make install

WORKDIR /opt/tools/bcftools-1.22/plugins
RUN wget https://raw.githubusercontent.com/freeseek/score/master/score.c && \
    wget https://raw.githubusercontent.com/freeseek/score/master/score.h && \
    wget https://raw.githubusercontent.com/freeseek/score/master/munge.c && \
    wget https://raw.githubusercontent.com/freeseek/score/master/liftover.c && \
    wget https://raw.githubusercontent.com/freeseek/score/master/metal.c && \
    wget https://raw.githubusercontent.com/freeseek/score/master/blup.c && \
    wget https://raw.githubusercontent.com/freeseek/score/master/pgs.c && \
    wget https://raw.githubusercontent.com/freeseek/score/master/pgs.mk

WORKDIR /opt/tools/bcftools-1.22
RUN sed -i '2254s/^/\/\//' plugins/pgs.c && \
    sed -i '2255s/^/\/\//' plugins/pgs.c

RUN ./configure \
        --prefix=/usr/local \
        --with-htslib=/opt/tools/htslib-1.22 \
        CPPFLAGS="-I/usr/include/suitesparse" \
        CFLAGS="-I/usr/include/suitesparse" && \
    make -j && make install

ENV BCFTOOLS_PLUGINS="/usr/local/libexec/bcftools"

# =====================================================================
# Install LDStore & FINEMAP
# =====================================================================
WORKDIR /tmp/install_tools

# Download and install LDStore v2.0
RUN wget http://www.christianbenner.com/ldstore_v2.0_x86_64.tgz && \
    tar -xzf ldstore_v2.0_x86_64.tgz && \
    mv ldstore_v2.0_x86_64/ldstore_v2.0_x86_64 /usr/local/bin/ldstore && \
    chmod +x /usr/local/bin/ldstore

# Download and install FINEMAP v1.4.2
RUN wget http://www.christianbenner.com/finemap_v1.4.2_x86_64.tgz && \
    tar -xzf finemap_v1.4.2_x86_64.tgz && \
    mv finemap_v1.4.2_x86_64/finemap_v1.4.2_x86_64 /usr/local/bin/finemap && \
    chmod +x /usr/local/bin/finemap

# Cleanup
RUN rm -rf /tmp/install_tools

# =====================================================================
# Install GCTA
# =====================================================================
WORKDIR /tmp/install_gcta

# Download the correct Kernel 3 version and install
RUN wget --user-agent="Mozilla/5.0" https://yanglab.westlake.edu.cn/software/gcta/bin/gcta-1.95.0-linux-kernel-3-x86_64.zip && \
    unzip gcta-1.95.0-linux-kernel-3-x86_64.zip && \
    mv gcta-1.95.0-linux-kernel-3-x86_64/gcta64 /usr/local/bin/gcta && \
    chmod +x /usr/local/bin/gcta

# Download SMR and install
RUN wget https://yanglab.westlake.edu.cn/software/smr/download/smr-1.3.1-linux-x86_64.zip && \
    unzip smr-1.3.1-linux-x86_64.zip && \
    mv smr-1.3.1-linux-x86_64/smr /usr/local/bin/smr && \
    chmod +x /usr/local/bin/smr

# Cleanup
RUN rm -rf /tmp/install_gcta

# =====================================================================
# Install MAGMA
# =====================================================================
COPY magma/magma /usr/local/bin/magma
RUN chmod +x /usr/local/bin/magma

# =====================================================================
# Install PostGWAS (Code & PIP Install)
# =====================================================================
# 1. Setup the directory
WORKDIR /opt/postgwas

# 2. COPY THE SOURCE CODE (This is what you were missing!)
COPY . /opt/postgwas

# 3. NOW run pip install, because setup.py is present
RUN micromamba run -n postgwas pip install --upgrade pip && \
    micromamba run -n postgwas pip install --no-deps --no-cache-dir -e .

# =====================================================================
# Final Config
# =====================================================================
ENV HOME=/tmp

# 1. Give the non-root user (mambauser) ownership of the code
RUN chown -R mambauser:mambauser /opt/postgwas

# 2. Switch to the non-root user
USER mambauser

# 3. Entrypoint
ENTRYPOINT ["micromamba", "run", "-n", "postgwas"]
CMD ["postgwas", "--help"]